ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.argus.ApplicationKt.module ]
  }
}

ollama {
  host = "http://localhost:11434"
  host = ${?OLLAMA_HOST}
  model = "gpt-oss:20b"
  model = ${?OLLAMA_MODEL}
}

slack {
  botToken = ""
  botToken = ${?SLACK_BOT_TOKEN}
}

github {
  token = ""
  token = ${?GITHUB_TOKEN}
}

launchdarkly {
  token = ""
  token = ${?LAUNCHDARKLY_TOKEN}
}

jira {
  baseUrl = ""
  baseUrl = ${?JIRA_BASE_URL}
  token = ""
  token = ${?JIRA_TOKEN}
}
